#!/usr/bin/env python3

import os 
import subprocess
import sys

name = input("=> Enter the app name: ")
image = input("=> Enter the icon full PATH: ")
imgcmd = subprocess.run(f"cp {image} /usr/share/icons",shell=True, capture_output=True, text=True)
if imgcmd.returncode != 0:
	print("Icon was not found in that path... ")
	sys.exit()
else: 
	image = image.split("/")[-1]
	image = f'/usr/share/icons/{image}'
	print(f"[\033[1;32m+\033[1;m] Icon sent to \033[1;32m{image}\033[1;m.")

	execu = input("=> Enter the executable command: ")

	#********************
	desktop = f'''
	[Desktop Entry]
	Version=1.0
	Name={name}
	Comment=Waves
	Exec={execu}
	Icon={image}
	Terminal=false
	Type=Application
	Categories=Utility;Application;
	'''
	#**********************


	with open(f"/usr/share/applications/{name}.desktop", "w+") as e:
		e.write(desktop)

	print("Done.")

